import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { getCountries, getEventById } from "@/lib/data";
import { acquireLock, getCached, setCached } from "@/lib/cache";
import { fetchCountryCoverage } from "@/app/api/country-sources/route";
import { isOverDailySummaryCap, recordSummaryGeneration } from "@/lib/external/anthropicUsage";
import type { Country, CountryCode, CountrySourceArticle, CoverageTier, Event } from "@/types";

// One Anthropic call on a cache miss (a few seconds), articles come from
// the already-cached coverage lookup — 30s is generous headroom.
export const maxDuration = 30;

// Bump the version segment when the prompt changes materially, so stale
// summaries generated by the old prompt age out instead of lingering.
// v2: tier-aware prompt — v1 mislabeled mentions-only coverage as the
// country's own press, which made the model (rightly) refuse.
const SUMMARY_CACHE_VERSION = "v2";
const SUMMARY_TTL_SECONDS = 24 * 60 * 60;

export type CountrySummaryResponse = {
  // null = no summary available (no coverage, no API key, cap reached,
  // or another instance is generating it right now — `pending: true`).
  summary: string | null;
  pending?: boolean;
};

function cacheKey(eventId: string, country: CountryCode): string {
  return `country-summary:${SUMMARY_CACHE_VERSION}:${eventId}:${country}`;
}

// Pure and exported for tests. Titles + publishers only — descriptions
// are not part of CountrySourceArticle, and five headlines with outlet
// names carry enough signal for a three-sentence framing summary.
//
// The prompt must be honest about what the articles are, mirroring the
// same tier distinction the UI already makes: "from-country" headlines
// are the country's own press, "mentioning-country" headlines are
// international coverage that merely mentions it. v1 described the
// fallback tier as the country's own media, and the model correctly
// refused to attribute framing — that refusal then rendered in the UI
// as if it were a summary.
export function buildSummaryPrompt(
  event: Event,
  country: Country,
  articles: CountrySourceArticle[],
  tier: CoverageTier
): string {
  const headlines = articles
    .slice(0, 5)
    .map((article) => `- "${article.title}" (${article.publisher}, ${article.publishedAt})`)
    .join("\n");
  const isMentionsOnly = tier === "mentioning-country";
  return [
    `International event: "${event.title}"`,
    `Event summary: ${event.summary}`,
    ``,
    isMentionsOnly
      ? `No outlets based in ${country.name} covered this directly. These are recent international headlines that mention ${country.name} in connection with the event:`
      : `Recent headlines from ${country.name}'s own press coverage of this event:`,
    headlines,
    ``,
    isMentionsOnly
      ? `In 2-3 plain sentences, summarize how ${country.name} figures in this international coverage — its role, position, or connection to the event as these headlines present it. Do not present this as ${country.name}'s own media framing. Do not invent details that the headlines don't support. Respond with the summary only, no preamble.`
      : `In 2-3 plain sentences, summarize how ${country.name}'s media is framing this event, based only on these headlines. Describe the angle and emphasis, not just the facts. Do not invent details that the headlines don't support. Respond with the summary only, no preamble.`,
  ].join("\n");
}

async function generateSummary(
  event: Event,
  country: Country,
  articles: CountrySourceArticle[],
  tier: CoverageTier,
  apiKey: string
): Promise<string | null> {
  const client = new Anthropic({ apiKey });
  try {
    await recordSummaryGeneration(`country-summary:${event.id}:${country.code}`);
    const response = await client.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 300,
      messages: [{ role: "user", content: buildSummaryPrompt(event, country, articles, tier) }],
    });
    const text = response.content
      .filter((block) => block.type === "text")
      .map((block) => block.text)
      .join("")
      .trim();
    return text.length > 0 ? text : null;
  } catch (error) {
    // A model outage or bad key must never break the sources view —
    // the client renders the coverage list without a summary.
    console.error(`[anthropic] summary generation failed for ${event.id}:${country.code}:`, error);
    return null;
  }
}

// Brief cache poll for callers that lost the generation lock: the
// winner usually finishes within a few seconds, so waiting lets the
// loser return the fresh summary instead of an empty "pending" state.
async function waitForCachedSummary(
  key: string,
  attempts: number,
  delayMs: number
): Promise<string | null> {
  for (let i = 0; i < attempts; i++) {
    await new Promise((resolve) => setTimeout(resolve, delayMs));
    const cached = await getCached<string>(key);
    if (cached) return cached;
  }
  return null;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const eventId = searchParams.get("eventId");
  const countryParam = searchParams.get("country");

  const allCountries = await getCountries();
  const country = allCountries.find((c) => c.code === countryParam);
  if (!eventId || !country) {
    return NextResponse.json({ summary: null } satisfies CountrySummaryResponse, { status: 400 });
  }

  const event = await getEventById(eventId);
  if (!event) {
    return NextResponse.json({ summary: null } satisfies CountrySummaryResponse, { status: 404 });
  }

  const key = cacheKey(eventId, country.code);
  const cached = await getCached<string>(key);
  if (cached) {
    return NextResponse.json({ summary: cached } satisfies CountrySummaryResponse);
  }

  // Ordered spend guards: no key configured → feature is off; daily cap
  // reached → stop spending until tomorrow. Both degrade to a
  // summary-less sources view rather than an error.
  const apiKey = process.env.ANTHROPIC_API_KEY ?? null;
  if (!apiKey) {
    return NextResponse.json({ summary: null } satisfies CountrySummaryResponse);
  }
  if (await isOverDailySummaryCap()) {
    console.log(`[anthropic] skipped (daily cap) — ${eventId}:${country.code}`);
    return NextResponse.json({ summary: null } satisfies CountrySummaryResponse);
  }

  // Coverage reuses the same 24h-cached lookup the sources view already
  // warmed, so this normally costs zero GNews calls.
  const { articles, tier } = await fetchCountryCoverage(
    event,
    country.code,
    process.env.GNEWS_API_KEY ?? null,
    "country-summary"
  );
  if (articles.length === 0) {
    return NextResponse.json({ summary: null } satisfies CountrySummaryResponse);
  }

  // Single-flight across all instances: under concurrent traffic only
  // the lock winner calls Anthropic; everyone else briefly polls the
  // cache for the winner's result. This is what keeps cost per
  // event+country at one call per 24h regardless of traffic.
  const gotLock = await acquireLock(`lock:${key}`, 30);
  if (!gotLock) {
    const summary = await waitForCachedSummary(key, 6, 1000);
    return NextResponse.json({
      summary,
      ...(summary ? {} : { pending: true }),
    } satisfies CountrySummaryResponse);
  }

  const summary = await generateSummary(event, country, articles, tier, apiKey);
  if (summary) {
    await setCached(key, summary, SUMMARY_TTL_SECONDS);
  }
  return NextResponse.json({ summary } satisfies CountrySummaryResponse);
}
